Many new features, partially implemented, poorly

diff --git a/theorycraft b/theorycraft
--- a/theorycraft
+++ b/theorycraft
@@ -5,6 +5,8 @@
 
 # TODO: [20191107] inherit global consul config from theory when terraform backend specifies consul but doesn't provide config (more procedurally, support inheriting global service configs where implementation requires but doesn't specify discrete parameters)
 # TODO: [20191107] allow ".vars" interpolation to support resolving values via child theorycraft calls
+# TODO: [20191108] add mysql - this is probably less of a fit, but there are processes we frequently run which could see an increase in efficiency via automation
+# TODO: [20191108] fix mysql to support multiple database definitions. and/or my.cnf...
 
 options_usage() {
     echo "Options:"
@@ -19,6 +21,7 @@ usage() {
 Supported Apps:
     new
     terraform
+    consul
     vault
     packer
     
@@ -73,11 +76,20 @@ packer_usage() {
 
 consul_usage() {
     echo "Consul Commands:"
+    echo "    acl"
     echo "    kv"
+    echo "        get"
+    echo "        put"
+    echo "        del"
     echo ""
     echo "Consul Parameters:"
     echo "    -d,--dc <name>            Selects the datacenter to run consul queries against"
     echo "    --token <token>           Override consul token from current theory"
+}
+
+mysql_usage() {
+    echo "MySQL Commands:"
+    echo "    backup"
 }
 
 loadTheory() {
@@ -115,6 +127,24 @@ loadTheory() {
         terraformjson=$(echo "${theoryjson}" | jq -r ".terraform")
         consuljson=$(echo "${theoryjson}" | jq -r ".consul")
         vaultjson=$(echo "${theoryjson}" | jq -r ".vault")
+        mysqljson=$(echo "${theoryjson}" | jq -r ".mysql")
+
+        if [ "${vaultjson}" != "null" ]
+        then
+            TC_VAULT_ADDR=$(echo "${vaultjson}" | jq -r ".address")
+            TC_VAULT_SKIP_VERIFY=$(echo "${vaultjson}" | jq -r ".skip_verify")
+
+            if [ "${TC_VAULT_ADDR}" != "null" ]
+            then
+                TC_HAS_VAULT=true
+                export VAULT_ADDR="https://${TC_VAULT_ADDR}"
+
+                if [ "${TC_VAULT_SKIP_VERIFY}" != "null" ]
+                then
+                    export VAULT_SKIP_VERIFY="${TC_VAULT_SKIP_VERIFY}"
+                fi
+            fi
+        fi
 
         if [ "${awsjson}" != "null" ]
         then
@@ -133,6 +163,16 @@ loadTheory() {
             if [ "${TC_TERRAFORM_BACKEND}" != "null" ]
             then
                 TC_HAS_TERRAFORM=true
+            fi
+        fi
+
+        if [ "${mysqljson}" != "null" ]
+        then
+            TC_MYSQL_PROFILES=$(echo "${mysqljson}" | jq -r ".profiles")
+
+            if [ "${TC_MYSQL_PROFILES}" != "null" ]
+            then
+                export TC_HAS_MYSQL=true
             fi
         fi
 
@@ -376,6 +416,8 @@ case ${APP} in
             exit 2
         fi
 
+        CMD=$1
+        shift
         case ${CMD} in
             new)
                 echo "new"
@@ -404,6 +446,7 @@ case ${APP} in
 
         # FIXME: [20191107] fix consul QRYSUFFIX when datacenter comes from theory
         QRYSUFFIX="?pretty"
+        XDATA=""
         while [[ $# -gt 1 ]] && [[ "$1" == "-"* ]]
         do
             opt="$1"
@@ -430,16 +473,38 @@ case ${APP} in
                 MODE=$1
                 shift
 
+                KVPATH=$1
+                shift
+
                 case ${MODE} in
                     list)
-                        QRY="$*${QRYSUFFIX}&keys"
+                        XMODE="GET"
+                        QRY="${KVPATH}${QRYSUFFIX}&keys"
                         ;;
                     get)
-                        QRY="$*${QRYSUFFIX}"
+                        XMODE="GET"
+                        QRY="${KVPATH}${QRYSUFFIX}"
+                        ;;
+                    # TODO: [20191108] fix the shit out of XDATA.
+                    put)
+                        XMODE="PUT"
+                        QRY="${KVPATH}${QRYSUFFIX}"
+                        XDATA="--data $1"
+                        shift
+                        ;;
+                    del)
+                        XMODE="DELETE"
+                        QRY="${KVPATH}${QRYSUFFIX}"
                         ;;
                 esac
 
-                curl -s -XGET -H "X-Consul-Token: ${TC_CONSUL_TOKEN}" "http://${TC_CONSUL_ADDRESS}/v1/kv/${QRY}"
+                curl -s -X${XMODE} -H "X-Consul-Token: ${TC_CONSUL_TOKEN}" "http://${TC_CONSUL_ADDRESS}/v1/kv/${QRY}" ${XDATA}
+                ;;
+            acl)
+                consul ${CMD} $*
+                ;;
+            api)
+                curl -s -XGET -H "X-Consul-Token: ${TC_CONSUL_TOKEN}" "http://${TC_CONSUL_ADDRESS}/v1/$*"
                 ;;
             help|*)
                 usage
@@ -447,10 +512,29 @@ case ${APP} in
         esac
         ;;
     vault)
+        if [ "${TC_HAS_VAULT}" != "true" ]
+        then
+            echo "Theory doesn't describe vault."
+            exit 2
+        fi
+
+        CMD=$1
+        shift
         case ${CMD} in
             login)
+                vault login
                 ;;
             get)
+                if [ $# -ne 2 ]
+                then
+                    usage
+                fi
+
+                __VAULT_PATH=$1
+                __VAULT_FIELD=$2
+                shift; shift;
+
+                vault kv get -field $__VAULT_FIELD $__VAULT_PATH
                 ;;
             put)
                 ;;
@@ -460,6 +544,8 @@ case ${APP} in
         esac
         ;;
     packer)
+        CMD=$1
+        shift
         case ${CMD} in
             build)
                 ;;
@@ -473,6 +559,34 @@ case ${APP} in
         esac
         ;;
     ansible)
+        CMD=$1
+        shift
+        ;;
+    mysql)
+        if [ "${TC_HAS_MYSQL}" != "true" ]
+        then
+            echo "Theory doesn't describe MySQL"
+            exit 1
+        fi
+
+        CMD=$1
+        shift
+        case ${CMD} in
+            backup)
+                if [ ! -d "./backups" ]
+                then
+                    echo "Couldn't find local backup destination within this universe."
+                    exit 2
+                fi
+                DATESTR=$(date +'%Y%m%d')
+                ITERATION=$(printf "%02d" $(( $(ls -laF backups/$1.$2.${DATESTR}-*.sql 2>/dev/null | wc -l)+1 )))
+                
+                mysqldump --login-path=${TC_MYSQL_PROFILE} $1 $2 > backups/$1.$2.${DATESTR}-${ITERATION}.sql
+                ;;
+            connect)
+                mysql --login-path=${TC_MYSQL_PROFILE}
+                ;;
+        esac
         ;;
     *)
         usage
